### ISSUE TITLE
Running "grunt nodeunit" fails because the actual message is 24 hours in the past

### ISSUE THREAD

**Issue by TC01** [magne4000/node-qtdatastream#2]
This is with Fedora 24, nodejs v4.4.6. I attempted to run the qtdatastream tests and got the [following error](https://paste.fedoraproject.org/386170/46717883/) (after cloning and running `npm install`).

Specifically it seems to fail because:

```
>> Actual:
>>     Date: Tue Jun 28 2016 01:35:31 GMT-0400 (EDT),
[...snip...]
>> Expected:
>>     Date: Wed Jun 29 2016 01:35:31 GMT-0400 (EDT),
```

I can confirm this also happens with nodejs v0.12.5 on Debian stretch.

**Comment by magne4000** [comment]
Yeah, I'm aware of this issue ... and it pass if you launch it later in the day. One of the approximation is probably not exactly correct

**Comment by magne4000** [comment]
Fixed with 0.6.6

**Comment by TC01** [comment]
FYI, this seems to still be occurring on 0.6.6, although the problem is different:

```
Testing node-qtdatastream_test.jsF
>> pingpong - no args
>> Message: Original and computed objects are not the same.
>> Actual:
[...snip...]
>>     Date1: Wed Jun 29 2016 06:00:00 GMT-0400 (EDT),
>>     Date2: Wed Aug 17 2016 13:02:47 GMT-0400 (EDT),
>>     Date3: Sat Nov 19 2016 00:42:20 GMT-0500 (EST),
[...]
>> Expected:
[...]
>>     Date1: Wed Jun 29 2016 06:00:00 GMT-0400 (EDT),
>>     Date2: Wed Jun 29 2016 20:00:00 GMT-0400 (EDT),
>>     Date3: Sat Nov 19 2016 00:42:20 GMT-0500 (EST),
```

This is currently occurring with node 4.6.1.

**Comment by magne4000** [comment]
Could you create another issue for this ?
