### ISSUE TITLE
Additional expected/actual date failures in unit tests

### ISSUE THREAD

**Issue by TC01** [magne4000/node-qtdatastream#3]
(Filing a new ticket as requested by @magne4000)

With node-qtdatastream 0.6.6 and node 4.6.1, running the unit tests seems to cause the following failure. Two of the dates seem to be correct, but Date2 seems to be wrong.

```
Testing node-qtdatastream_test.jsF
>> pingpong - no args
>> Message: Original and computed objects are not the same.
>> Actual:
[...snip...]
>>     Date1: Wed Jun 29 2016 06:00:00 GMT-0400 (EDT),
>>     Date2: Wed Aug 17 2016 13:02:47 GMT-0400 (EDT),
>>     Date3: Sat Nov 19 2016 00:42:20 GMT-0500 (EST),
[...]
>> Expected:
[...]
>>     Date1: Wed Jun 29 2016 06:00:00 GMT-0400 (EDT),
>>     Date2: Wed Jun 29 2016 20:00:00 GMT-0400 (EDT),
>>     Date3: Sat Nov 19 2016 00:42:20 GMT-0500 (EST),
```

**Comment by magne4000** [comment]
Do you reproduce this everytime you launch `grunt nodeunit` ? Because I'm unable to reproduce this situation with `4.6.1` or `4.6.2`.

**Comment by magne4000** [comment]
OK, I reproduced it, it fails with `TZ='EST'`
