### ISSUE TITLE
License confirmation

### ISSUE THREAD

**Issue by TC01** [magne4000/node-qtdatastream#4]
Hi,

As part of my (slowly ongoing) efforts to package quassel-webserver for Fedora, I'm currently packaging nodejs-qtdatastream. In the Fedora review process, I was asked [to confirm the licensing](https://bugzilla.redhat.com/show_bug.cgi?id=1397621), namely to confirm that all code/contents are indeed under the MIT license, since the following files didn't have license headers:

>    package/lib/iterator.js
>    package/lib/util.js
>    package/test/node-qtdatastream_test.js

Thanks in advance!

**Comment by magne4000** [comment]
Hi @TC01, sorry for the delay. I confirm that all the file (including those cited) are under MIT license.
I'll add the headers in those files too.
